/******************************************************************************
*%%%% function name
*------------------------------------------------------------------------------
*
*	SYNOPSIS	<return type> <function name> <arguments>
*
*	FUNCTION	<description>
*
*	INPUTS		<input 1>				<description>
*
*	RESULT		<output>				<description>
*
*	NOTES		<Special notes about the function>
*
*	CHANGED		PROGRAMMER		REASON
*	-------		----------		------
*	xx.xx.97	<Name>			<Description>
*
*%%%**************************************************************************/
