/******************************************************************************
*%%%% mr_inc.h
*------------------------------------------------------------------------------
*
*	Root list of header files required for use of the Millennium API. This file
*	is only included by mr_all.h.
*
*	Note that this file doesn't have any multiple inclusion checking in it. 
*	This is intentional, as we need to include it twice for typedef processing.
*
*	CHANGED		PROGRAMMER		REASON
*	-------  	----------  	------
*	11.06.97	Dean Ashton		Created
*
*%%%**************************************************************************/


#include	"mr_mem.h"
#include	"mr_file.h"
#include	"mr_over.h"
#include	"mr_input.h"
#include	"mr_frame.h"
#include	"mr_obj.h"

#include	"mr_vram.h"
#include	"mr_coll.h"
#include	"mr_mof.h"
#include	"mr_ot.h"
#include	"mr_mesh.h"
#include	"mr_font.h"
#include	"mr_disp.h"
#include	"mr_light.h"
#include	"mr_part.h"
#include	"mr_sprt.h"
#include	"mr_fx.h"
#include	"mr_view.h"
#include	"mr_misc.h"
#include	"mr_quat.h"
#include	"mr_pres.h"
#include	"mr_splin.h"
#include	"mr_anim.h"
#include	"mr_anim2.h"
#include	"mr_anim3.h"
#include	"mr_stat.h"
#include	"mr_math.h"
#include	"mr_debug.h"
#include	"mr_sound.h"

#include	"mr_fast.h"

#include	"mr_crash.h"

