#ifndef _STRING_H
#define _STRING_H

/*****************************************************************
 * -*- c -*-
 * $RCSfile: string.h,v $
 *
 * Copyright (C) 1994, 1995 by Sony Computer Entertainment Inc.
 * All Rights Reserved.
 *
 * Sony Computer Entertainment Inc. R & D Division
 *
 * $Id: string.h,v 1.1 1995/04/04 12:30:26 kaol Exp $
 *
 *****************************************************************/
/*
 * $PSLibId: Run-time Library Release 4.0$
 */

#include <strings.h>

/* ----------------------------------------------------------------
 *	End on File
 * ---------------------------------------------------------------- */
#endif /* _STRING_H_ */
/* DON'T ADD STUFF AFTER THIS */
