// gen_gold_frog.h
// written at Tue Sep  2 17:43:07 1997

// by xmof version 1.33

enum GEN_GOLD_FROG_KEYFRAME_SET_ACTION {
	GEN_GOLD_FROG_HOP,
	GEN_GOLD_FROG_CROAK,
	GEN_GOLD_FROG_LOOKAROUND,
	GEN_GOLD_FROG_EXCITED,
	GEN_GOLD_FROG_BACKFLIP,
	GEN_GOLD_FROG_SIT,
};
