/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////
//
// /usr/people/frogger/gfx/models/generic/gen_frog.h
//        written @ Tue Sep 02 09:35:57 1997
//        by aconv3, Author ICE
//
/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////


/////////////// MODEL SET : gen_frog ///////////////

#define GEN_FROG (0)

// MODEL : gen_frog
#define GEN_FROG__0 (0)

enum GEN_FROG_PARTS {
    TAIL,
    LEFT_THIGH,
    LEFT_CALF,
    LEFT_FOOT,
    RIGHT_THIGH,
    RIGHT_CALF,
    RIGHT_FOOT,
    HEAD,
    LEFT_BICEP,
    LEFT_HAND,
    LEFT_FOREARM,
    RIGHT_BICEP,
    RIGHT_FOREARM,
    RIGHT_HAND,
    JAW,
    THROAT,
};

// Cel_Set : gen_frog_keyframe_set
#define GEN_FROG_KEYFRAME_SET (0)

enum GEN_FROG_KEYFRAME_SET_ACTION {
     GEN_FROG_AUTOHOP,
     GEN_FROG_BACKFLIP,
     GEN_FROG_SQUISHED,
     GEN_FROG_WAIT1,
     GEN_FROG_TIMEOUT,
     GEN_FROG_STRUGGLE,
     GEN_FROG_FALLING,
     GEN_FROG_TRIGGER,
     GEN_FROG_DROWN,
     GEN_FROG_COMPLETE,
     GEN_FROG_BITTEN,
     GEN_FROG_FREEFALL,
     GEN_FROG_FLOP,
     GEN_FROG_OUCH,
     GEN_FROG_PANT,
     GEN_FROG_ROLL,
     GEN_FROG_HOP,
     GEN_FROG_SUPERJUMP,
     GEN_FROG_PANT2,
     GEN_FROG_WAIT3,
     GEN_FROG_SUPERHOP,
     GEN_FROG_WAIT2,
     GEN_FROG_SLIP,
     GEN_FROG_POP,
     GEN_FROG_SLIPRIGHT,
     GEN_FROG_SLIPLEFT,
     GEN_FROG_CRASH,
     GEN_FROG_PHEW,
     GEN_FROG_LOOKDOWN,
     GEN_FROG_LOOKUP,
     GEN_FROG_LOOKLEFT,
     GEN_FROG_LOOKRIGHT,
     GEN_FROG_DANCE,
     GEN_FROG_MOWN,
};


// Transform Sets
enum GEN_FROG_TFORM_SETS {
     GEN_FROGGEN_FROG_AUTOHOP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_BACKFLIP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_SQUISHED_TRANSFORM_SET,
     GEN_FROGGEN_FROG_WAIT1_TRANSFORM_SET,
     GEN_FROGGEN_FROG_TIMEOUT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_STRUGGLE_TRANSFORM_SET,
     GEN_FROGGEN_FROG_FALLING_TRANSFORM_SET,
     GEN_FROGGEN_FROG_TRIGGER_TRANSFORM_SET,
     GEN_FROGGEN_FROG_DROWN_TRANSFORM_SET,
     GEN_FROGGEN_FROG_COMPLETE_TRANSFORM_SET,
     GEN_FROGGEN_FROG_BITTEN_TRANSFORM_SET,
     GEN_FROGGEN_FROG_FREEFALL_TRANSFORM_SET,
     GEN_FROGGEN_FROG_FLOP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_OUCH_TRANSFORM_SET,
     GEN_FROGGEN_FROG_PANT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_ROLL_TRANSFORM_SET,
     GEN_FROGGEN_FROG_HOP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_SUPERJUMP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_PANT2_TRANSFORM_SET,
     GEN_FROGGEN_FROG_WAIT3_TRANSFORM_SET,
	 GEN_FROGGEN_FROG_SUPERHOP_TRANSFORM_SET,
	 GEN_FROGGEN_FROG_WAIT2_TRANSFORM_SET,
     GEN_FROGGEN_FROG_SLIP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_POP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_SLIPRIGHT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_SLIPLEFT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_CRASH_TRANSFORM_SET,
     GEN_FROGGEN_FROG_PHEW_TRANSFORM_SET,
     GEN_FROGGEN_FROG_LOOKDOWN_TRANSFORM_SET,
     GEN_FROGGEN_FROG_LOOKUP_TRANSFORM_SET,
     GEN_FROGGEN_FROG_LOOKLEFT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_LOOKRIGHT_TRANSFORM_SET,
     GEN_FROGGEN_FROG_DANCE_TRANSFORM_SET,
     GEN_FROGGEN_FROG_MOWN_TRANSFORM_SET,
};

