/******************************************************************************
*%%%% mr_all.h
*------------------------------------------------------------------------------
*
*	Simple hook to API header files, created locally.
*
*	CHANGED		PROGRAMMER		REASON
*	-------  	----------  	------
*	02.08.96	Dean Ashton		Created
*
*%%%**************************************************************************/

#ifndef		__MR_ALL_TEMP_H
#define		__MR_ALL_TEMP_H

#include        "api.src/mr_all.h"

#endif		//__MR_ALL_TEMP_H
