/******************************************************************************
*%%%% scripts.c
*------------------------------------------------------------------------------
*
*	This module contains main script enums and tables for entities throughout 
*	the game. The actual scripts themselves are contained within the respective
*	theme c and h files.
*
*	CHANGED		PROGRAMMER		REASON
* 	-------  	----------  	------
*	12.05.97	Martin Kift		Created
*	22.05.97	Martin Kift		Moved out most of scripts into theme files.
*
*%%%**************************************************************************/

#include "scripts.h"
#include "scripter.h"
#include "frog.h"
#include "sound.h"
#include "ent_all.h"

//------------------------------------------------------------------------------------------------
// Main script lookup table
//------------------------------------------------------------------------------------------------
MR_LONG*	Scripts[] = {
		NULL,			
		script_org_crocodile,
		script_org_car_blue,
		script_org_lorry,
		script_org_snake,
		script_sub_swan,
		script_sub_swan_sfx,
		script_org_truck,
		script_sky_helium_balloon_waiting,
		script_sky_helium_balloon_rising,
		script_sky_helium_balloon_sinking,
		script_sky_helium_balloon_popping,
		script_swp_nuclear_barrel_waiting,
		script_swp_nuclear_barrel_ejecting,
		script_log_splash,
		script_org_bonus_fly,
		script_org_bonus_fly_collected,
		script_swp_waste_barrel_waiting,
		script_swp_waste_barrel_spinning,
		script_swp_bobbing_waste_barrel,
		script_sky_rubber_balloon_waiting,
		script_sky_rubber_balloon_rising,
		script_sky_rubber_balloon_sinking,
		script_sky_rubber_balloon_popping,
		script_sub_lilly_pad,
		script_sub_lawn_mower,
		script_sub_lawn_mower_kill_frogger,
		script_cav_rockfallfloor_waiting,
		script_cav_rockfallfloor_falling,
		script_sky_helicopter,
		script_org_car_purple,
		script_org_bull_dozer,
		script_sky_homing_bird,
		script_sky_homing_bird_hit_frog,
		script_org_lorry_sfx,
		script_org_car_blue_sfx,
		script_org_car_purple_sfx,
		script_org_truck_sfx,
		script_org_bull_dozer_sfx,
		script_org_road_noise,
		script_org_water_noise,
		script_swp_oil_drum,
		script_swp_pallet,
		script_swp_sunkcar,
		script_swp_stat_pipe,
		script_swp_stat_pipe_big_str,
		script_swp_stat_pipe_hole,
		script_des_bison,
		script_des_bison_sfx,
		script_des_lizard,
		script_cav_bat,
		script_cav_bat_sfx,
		script_cav_vamp_bat,
		script_cav_vamp_bat_sfx,
		script_turtle,
		script_turtle_no_dive,
		script_sky_bird1_1,
		script_sky_bird1_call_sfx,
		script_sky_bird2_1,
		script_sky_bird2_call_sfx,
		script_sky_bird3_1,
		script_sky_bird3_call_sfx,
		script_sky_bird4_1,
		script_sky_bird4_call_sfx,
		script_sky_jet1,
		script_sky_jet3,
		script_sky_biplane,
		script_vol_mechanism,
		script_sub_car_blue,
		script_sub_car_blue_sfx,
		script_sub_lorry,
		script_sub_lorry_sfx,
		script_sub_truck,
		script_sub_truck_sfx,
		script_swp_water_noise,
		script_sub_snake,
		script_sub_road_noise,
		script_sub_water_noise,
		script_jun_floating_tree,
		script_jun_floating_tree_moving,
		script_sub_small_bird,
		script_swp_rat,
		script_swp_rat_sfx,
		script_jun_hippo,
		script_jun_hippo_no_dive,
		script_sub_snake_turn,
		script_sub_pelican,
		script_sub_pelican_call_sfx,
		script_for_squirrel,
		script_for_squirrel_sfx,
		script_for_owl,
		script_for_owl_sfx,
		script_for_river_noise,
		script_vol_cog_noise,
		script_vol_lava_noise,
		script_vol_spinner,
		script_jun_water_noise,
		script_jun_monkey,
		script_jun_monkey_sfx,
		script_jun_monkey_scream_sfx,
		script_jun_crocodile,
		script_jun_hippo_sfx,
		script_jun_scorpion,
		script_jun_rhino,
		script_jun_rhino_sfx,
		script_jun_piranaha,
		script_swp_mutant_fish,
		script_cav_spider,
		script_vol_furnace_platform,
		script_swp_raccoon,
		script_swp_snail,
		script_des_beetle,
		script_des_salamander,
		script_swp_pelican,
		script_swp_pelican_call_sfx,
		script_for_swan,
		script_for_swan_sfx,
		script_vol_lava_spray,
		script_sky_magical_popping_balloon,
		script_sky_magical_popping_balloon_pop,
		script_des_snake,
		script_org_turtle_swim,
		};	

MR_VOID	(*script_callback_functions[])(LIVE_ENTITY*) = {
	ScriptCBFrogTrafficSplat,
	ScriptCBLogSplash,
	ScriptCBDiveColourChange,
	ScriptCBSwpOilDrum,
	ScriptCBSwpPallet,
	ScriptCBSwpSunkCar,
	ScriptCBSwpStatPipe,
	ScriptCBSwpStatPipeBigStr,
	ScriptCBHitTurtle,
	ScriptCBSkyBird1Call,
	ScriptCBSkyBird2Call,
	ScriptCBSkyBird3Call,
	ScriptCBSkyBird4Call,
	ScriptCBSkyFrogHelicopter,
	ScriptCBSkyHeliumBalloon,
	ScriptCBSubLillyPad,
	ScriptCBJunHippoHit,
	ScriptCBJunPiranaha,
	ScriptCBSwpMutantFish,
	ScriptCBSwpRaccoon,
	ScriptCBSwpPelicanCall,
	};
