//---------------------------------------------------------------------------
//
//	SOUND.H
//
//		Definitions for sound data
//
//---------------------------------------------------------------------------

#ifndef __sound_h
#define __sound_h

#include "entity.h"

// Enums ----------------------------------------------------------------

// List of VAB's.
enum					
	{			
	VAB_GENERIC,
	VAB_CAVES,
	VAB_DESERT,
	VAB_FOREST,
	VAB_JUNGLE,
	VAB_ORIGINAL,	
	VAB_DELETED,			// Has been removed, but is still needed for order.
	VAB_SWAMP,
	VAB_SKY,
	VAB_SUBURBIA,
	VAB_INDUSTRIAL,
	VAB_SELECT,
	};

// List of groups.
enum
{
	SFX_GROUP_FROGGER,
	SFX_GROUP_ENTITY,

	SFX_GROUP_UNKNOWN,
	// Options.
	SFX_GROUP_SELECT,
};

// List of samples split by theme.
enum
{
	// In the GENERIC VAB.
	SFX_GEN_FLY_BUZZ,
	SFX_GEN_FROG_DROWN1,
	SFX_GEN_FROG_DROWN2,
	SFX_GEN_FROG_CROAK,
	SFX_GEN_FROG_FALL1,
	SFX_GEN_FROG_FLY_GULP,
	SFX_GEN_FROG_HOP,
	SFX_GEN_FROG_SUPER_HOP,
	SFX_MUSIC_LEVEL_COMPLETE,
	SFX_MUSIC_TARGET_COMPLETE,
	SFX_MUSIC_TIMEOUT,
	SFX_GEN_ENTITY_DIVE1,
	SFX_GEN_FROG_HIT_GROUND,
	SFX_GEN_FROG_SPLAT,
	SFX_GEN_FROG_THUD,
	SFX_GEN_FROG_SPLASH1,
	SFX_GEN_BABY_FROG,
	SFX_GEN_FROG_EXPLODE,
	SFX_GEN_GOLD_FROG_CROAK,
	SFX_GEN_FROG_SPLASH2,
	SFX_GEN_FROG_SLURP,
	SFX_GEN_FLY_BUZZ02,
	SFX_MUSIC_GOLD_COMPLETE,
	SFX_MUSIC_DRUMLOAD,
	SFX_GEN_CLOCK_TICK,
	SFX_GEN_CLOCK_TOCK,
	SFX_GEN_EXTRA_LIFE,
	// These's are samples played back at different pitchs to create 'new' sounds.
	SFX_GEN_BABY_FROG_HOP,
	SFX_GEN_FROG_CROAK_REPEAT,
	SFX_GEN_FROG_COLL_STACK,
	SFX_GEN_FROG_STUNNED,
	SFX_GEN_FROG_SCARED,

	// In the CAVES VAB.
	SFX_CAV_BAT,
	SFX_CAV_FIREFLY,
	SFX_CAV_LAVADROP_BUBBLE,
	SFX_CAV_LAVADROP_FLOORHIT,
	SFX_CAV_ROCKFALLFLOOR,
	SFX_CAV_ROPEBRIDGE01,
	SFX_CAV_ROPEBRIDGE02,
	SFX_CAV_SLIME,
	SFX_CAV_SNAIL_MOVE,
	SFX_CAV_SNAIL_SLIME,
	SFX_CAV_SPIDER,
	SFX_CAV_VAMP_BAT,
	SFX_CAV_GLOW_WORM,
	SFX_CAV_FROG_SLIDE,

	// In the DESERT VAB
	SFX_DES_BISON,
	SFX_DES_BISON_NOISE,
	SFX_DES_CRACK,
	SFX_DES_EARTHQUAKE,
	SFX_DES_ROCK_BOUNCE,
	SFX_DES_ROCK_BREAK,
	SFX_DES_ROCK_ROLL,
	SFX_DES_HOLE01,
	SFX_DES_HOLE02,
	SFX_DES_LIZARD,
	SFX_DES_SALAMANDER,
	SFX_DES_SANDSTORM,
	SFX_DES_SNAKE_HISS,
	SFX_DES_SNAKE_RATTLE,
	SFX_DES_VULTURE,
	SFX_DES_TUMBLEWEED,
	SFX_DES_CROCODILE_SNAP,
	SFX_DES_FROG_CROC_MUNCH,

	// In the FOREST VAB
	SFX_FOR_BEE_BUZZ,
	SFX_FOR_BEE_STING,
	SFX_FOR_BRANCH_SNAP,
	SFX_FOR_RIVER,
	SFX_FOR_OWL01,
	SFX_FOR_OWL02,
	SFX_FOR_SQUIRREL,
	SFX_FOR_BIRD_WING,
	SFX_FOR_BIRD_WING_FRENZIED,
	SFX_FOR_SWAN_CALL,
	SFX_FOR_SWAN_CALL_FRENZIED,

	// In the JUNGLE VAB
	SFX_JUN_BIRD_CALL,
	SFX_JUN_BIRD_CALL_FRENIZED,
	SFX_JUN_BIRD_WING,
	SFX_JUN_BIRD_WING_FRENIZED,
	SFX_JUN_BITE,
	SFX_JUN_BITE_SWALLOW,
	SFX_JUN_FROG_CROC_MUNCH,
	SFX_JUN_FROG_CROC_SNAP,
	SFX_JUN_HIPPO,
	SFX_JUN_MONKEY_CHAT,
	SFX_JUN_MONKEY_SCREAM,
	SFX_JUN_RHINO_GROWL,
	SFX_JUN_SCORPION,
	SFX_JUN_WATER_NOISE,
	SFX_OUT_FROG_EXPLODE,
	SFX_OUT_STONE_RUMBLE_REPEAT,
	SFX_OUT_STONE_RUMBLE,
	SFX_JUN_PLANT_SNAP,

	// In the ORIGINAL VAB
	SFX_ORG_BULLDOZER_HORN,
	SFX_ORG_BULLDOZER_HORN02,
	SFX_ORG_CAR_HORN01,
	SFX_ORG_CAR_HORN02,
	SFX_ORG_CROCODILE_SNAP,
	SFX_ORG_FROG_CROC_MUNCH,
	SFX_ORG_ROAD_NOISE,
	SFX_ORG_SNAKE_HISS,
	SFX_ORG_WATER_NOISE,
	SFX_ORG_LORRY_HORN01,
	SFX_ORG_LORRY_HORN02,

	// In the SWAMP VAB
	SFX_SWP_CRUSHER,
	SFX_SWP_NUCLEAR_BARREL_EXPLODE,
	SFX_SWP_NUCLEAR_BARREL_GEIGER,
	SFX_SWP_HOLLOW_THUD,
	SFX_SWP_RAT,
	SFX_SWP_STAT_FLUME,
	SFX_SWP_STAT_MARSH,
	SFX_SWP_STAT_PIPE_HOLE,
	SFX_SWP_STAT_WEIR,
	SFX_SWP_ACID_DRIP,
	SFX_SWP_WATERNOISE,
	SFX_SWP_SLIPPING,
	SFX_SWP_BIRD_WING,
	SFX_SWP_BIRD_WING_FRENZIED,
	SFX_SWP_PELICAN_CALL,
	SFX_SWP_PELICAN_CALL_FRENZIED,
	SFX_SWP_SNAIL_MOVE,
	
	// In the SKY VAB
	SFX_SKY_BIPLANE1,
	SFX_SKY_BIPLANE_BANNER1,
	SFX_SKY_PELICAN_CALL,
	SFX_SKY_PELICAN_CALL_FRENZIED,
	SFX_SKY_BIRD1_WING,
	SFX_SKY_BIRD1_WING_FRENZIED,
	SFX_SKY_CROW_CALL,
	SFX_SKY_CROW_CALL_FRENZIED,
	SFX_SKY_SEAGULL_CALL,
	SFX_SKY_SEAGULL_CALL_FRENZIED,
	SFX_SKY_GOOSE_CALL,
	SFX_SKY_GOOSE_CALL_FRENZIED,
	SFX_SKY_BIRD_SMALL1,
	SFX_SKY_FLOCKING1,
	SFX_SKY_HAWK_CALL,
	SFX_SKY_HAWK_DIVE,
	SFX_SKY_HELICOPTER_FROG_KILL,
	SFX_SKY_HELICOPTER_NOISE,
	SFX_SKY_HELIUM_BALLOON_POP,
	SFX_SKY_JET1,
	SFX_SKY_JET3,
	SFX_SKY_DUCK_CALL,
	SFX_SKY_DUCK_CALL_FRENZIED,
	SFX_SKY_RUBBER_BALLOON_FART,
	SFX_SKY_RUBBER_BALLOON_SQUEAK,
	SKY_WIND,

	// In the SUBURBIA VAB
	SFX_SUB_CAR_HORN01,
	SFX_SUB_CAR_HORN02,
	SFX_SUB_DOG_BARK,
	SFX_SUB_DOG_EAT,
	SFX_SUB_DOG_GROWL,
	SFX_SUB_FROG_MOWED,
	SFX_SUB_LORRY_HORN01,
	SFX_SUB_LORRY_HORN02,
	SFX_SUB_MOWER,
	SFX_SUB_SWAN_CALL,
	SFX_SUB_PELICAN_WING,
	SFX_SUB_SNAKE_HISS,
	SFX_SUB_WATER_NOISE,
	SFX_SUB_ROAD_NOISE,
	SFX_SUB_PELICAN_CALL,

	// In the INDUSTRAIL VAB
	SFX_IND_CHAIN,
  	SFX_IND_COGS,
  	SFX_IND_HYDRAULIC,
  	SFX_IND_LAVA,
  	SFX_IND_METAL_SMASH,
  	SFX_IND_PLATFORM_FALLING,
  	SFX_IND_STREAM_JET3,
  	SFX_IND_SWITCH,

	// In the SELECT VAB
	SFX_SEL_CANCEL,
	SFX_SEL_HI_SCORE_COUNT,
	SFX_SEL_HI_SCORE_COUNT0,
	SFX_SEL_HI_SCORE_FINISH,
	SFX_SEL_SPLASH,
};

enum{
	ENTITY_SOUND_OFF,
	ENTITY_SOUND_ON,
	};

// Externals ----------------------------------------------------------------

extern	MRSND_VAB_INFO		gVABInfo[];
extern	MRSND_GROUP_INFO	gGroupInfo[];
extern	MRSND_SAMPLE_INFO	gSampleInfo[];
extern	MR_LONG				MusicPitchTable[60][2];

// Phototypes ----------------------------------------------------------------

extern MR_VOID	TestSoundEffects(MR_VOID);
extern MR_VOID	InitialiseVab(MR_VOID);
extern MR_VOID	PlaySoundDistance(LIVE_ENTITY*, MR_LONG, MR_LONG);
extern MR_VOID	PlayMovingSound(LIVE_ENTITY*, MR_LONG, MR_LONG, MR_LONG);
extern MR_VOID	KillMovingSound(LIVE_ENTITY*);

#endif		// __sound_h